import CommonLayout from "@/components/layouts/commonLayout";
import { ViewPage } from "@/components/pages/view";
import Head from "next/head";
import React from "react";

const ViewIdPage = () => {
  return (
    <>
      <Head>
        <title>View Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CommonLayout>
        <ViewPage />
      </CommonLayout>
    </>
  );
};

export default ViewIdPage;
