import CommonLayout from "@/components/layouts/commonLayout";
import { MapPage } from "@/components/pages/openmap";
import Head from "next/head";
import React from "react";

const AuthPage = () => {
  return (
    <>
      <Head>
        <title>Auth Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CommonLayout>
        <MapPage />
      </CommonLayout>
    </>
  );
};

export default AuthPage;
