import CommonLayout from "@/components/layouts/commonLayout";
import { AdminPage as Admin } from "@/components/pages/admin";
import Head from "next/head";
import React from "react";

const AdminPage = () => {
  return (
    <>
      <Head>
        <title>Admin Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CommonLayout>
        <Admin />
      </CommonLayout>
    </>
  );
};

export default AdminPage;
